[bot.private-defaults]
# Allow configure by default (Turn it of if you'll want to disable private)
# admin-can-change-settings = true

# Allow tools commands (/draw, /analyze, etc...)
# allow-tools-commands = true
# allow-mention = true
# allow-reply = true

# For private chats - Always answer something
random-answer-probability = 1
# The only user in Private chat is admin
random-answer-to-admin = true

# No spam possible in private chats
detect-spam = false

[bot.chat-defaults]
# Can chat admins change channel-specific bot settings?
# admin-can-change-settings = true

# Allow tools commands (/draw, /analyze, etc...)
# allow-tools-commands = true
# Delete message with commands, which deniend in chat (for flood protection purposes)
# delete-denied-commands = false

# Allow reaction in bot mention (by username and by name)
# allow-mention = true
# Allow reaction on reply of bot message
# allow-reply = true

# Probability of random answer to any message (set 0 for disable, 1 for always)
# For chat it should be very rare event
# random-answer-probability = 0.01
# In case of random answer - answer to chat admin messages?
# random-answer-to-admin = true

# Automatically detect and delete spam messages
# detect-spam = false

[bot.defaults]
# Can chat admins change channel-specific bot settings?
admin-can-change-settings = true
# Bot nicknames for mention purposes. Comma-separated list
bot-nicknames = "–ì—Ä–æ–º–æ–∑–µ–∫–∞, Gro"
# Message format for LLM, currently supported: `text`, `json`, `smart`
llm-message-format = "smart"
# Can we use tools
use-tools = true
# Should we parse images via LLM
parse-images = true

# Should we save attachments to S3 for future using? (currently usefull for ResenderHandler only)
save-attachments = false
# Prefix for saved attachments
save-prefix = "media-"

# Allow tools commands (/draw, /analyze, etc...)
allow-tools-commands = true
# Delete message with commands, which deniend in chat (for flood protection purposes)
delete-denied-commands = false

# Allow non-admins to send /spam and /unban commands
allow-user-spam-command = false
# Automatically detect and delete spam messages
detect-spam = false
# If user has more than this amount of messages in chat, do not check it for spam (0 - always check)
auto-spam-max-messages = 10
# In case of spam - delete all known user messages
spam-delete-all-user-messages = true
# Minimal SPAM Score to block user and delete it's messages
spam-ban-treshold = 90
# Minimal SPAM Score to add warn message
spam-warn-treshold = 60
# Allow to block old (with more, than `auto-spam-max-messages` messages) users with /spam command
allow-mark-spam-old-users = false

# Bayes filter settings
bayes-enabled = true
bayes-min-confidence = 0.5
bayes-auto-learn = true
# Should we use trigrams for Bayes filter? (Usefull only in case of lots of learned messages)
bayes-use-trigrams = false

# Allow reaction in bot mention (by username and by name)
allow-mention = true
# Allow reaction on reply of bot message
allow-reply = true

# Probability of random answer to any message (set 0 for disable, 1 for always)
random-answer-probability = 0.01
# In case of random answer - answer to chat admin messages?
random-answer-to-admin = true

tools-used-prefix        = "üõ†"
fallback-happened-prefix = "ü§ñ"

chat-model                      = "openrouter/mistral-7b-instruct:free"
fallback-model                  = "openrouter/gemma-3-12b-it:free"
summary-model                   = "openrouter/gemma-3-12b-it:free"
summary-fallback-model          = "openrouter/deepseek-chat-v3.1:free"
image-parsing-model             = "openrouter/gemma-3-27b-it:free"
image-parsing-fallback-model    = "openrouter/qwen3-vl-235b-a22b-instruct"
image-generation-model          = "yandex-art"
image-generation-fallback-model = "openrouter/gemini-2.5-flash-image"
condensing-model                = "openrouter/gemma-3-27b-it:free"

summary-prompt     = "–°—É–º–º–∞—Ä–∏–∑–∏—Ä—É–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å—Å–∫–∏–µ —Å–æ–æ–±—â–µ–Ω–∏—è, –ø—Ä–µ–¥–æ—Å—Ç–∞–≤–ª–µ–Ω–Ω—ã–µ –≤ JSON —Ñ–æ—Ä–º–∞—Ç–µ. –£–∫–∞–∑—ã–≤–∞–π –≤—Ä–µ–º—è –Ω–∞—á–∞–ª–∞ –∏ –∫–æ–Ω—Ü–∞ –æ–±—Å—É–∂–¥–µ–Ω–∏—è –∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π, –∫—Ç–æ –æ–±—Å—É–∂–¥–∞–ª."
parse-image-prompt = "–ü–æ–¥—Ä–æ–±–Ω–æ –æ–ø–∏—à–∏, —á—Ç–æ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–æ –Ω–∞ –∫–∞—Ä—Ç–∏–Ω–∫–µ"
chat-prompt        = """
–¢—ã - –ü—Ä–∏–Ω–Ω–∏: –≤–∞–π–±–æ–≤—ã–π, –Ω–æ —É–º–Ω—ã–π –ø–∏–Ω–≥–≤–∏–Ω –∏–∑ Disgaea –º—É–∂—Å–∫–æ–≥–æ –ø–æ–ª–∞.
"""
# Prompt suffix for chat model
# We allow admins to change only first part of prompt
# So we'll be sure that bot understand format of messages and so on
chat-prompt-suffix = """
–°–æ–æ–±—â–µ–Ω–∏—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π —É–∫–∞–∑–∞–Ω—ã –≤ JSON-—Ñ–æ—Ä–º–∞—Ç–µ, –≥–¥–µ:
* `login` - –õ–æ–≥–∏–Ω –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è.
* `name` - –ü–æ–ª–Ω–æ–µ –∏–º—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è.
* `date` - –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ —Å–æ–æ–±—â–µ–Ω–∏—è (–≤ UTC).
* `messageId` - ID —Å–æ–æ–±—â–µ–Ω–∏—è.
* `type` - –¢–∏–ø —Å–æ–æ–±—â–µ–Ω–∏—è: `text`, `image`, `sticker`
* `text` - –¢–µ–∫—Å—Ç —Å–æ–æ–±—â–µ–Ω–∏—è.
* `replyId` - ID —Å–æ–æ–±—â–µ–Ω–∏—è, –Ω–∞ –∫–æ—Ç–æ—Ä–æ–µ –æ—Ç–≤–µ—á–∞–µ—Ç –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å. –£–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è, –µ—Å–ª–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –æ—Ç–≤–µ—á–∞–µ—Ç –Ω–∞ —Å–æ–æ–±—â–µ–Ω–∏–µ.
* `quote` - –¶–∏—Ç–∞—Ç–∞. –£–∫–∞–∑—ã–≤–∞–µ—Ç—Å—è, –µ—Å–ª–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –≤ —Å–≤–æ—ë–º —Å–æ–æ–±—â–µ–Ω–∏–∏ –ø—Ä–æ—Ü–∏—Ç–∏—Ä–æ–≤–∞–ª –¥—Ä—É–≥–æ–µ —Å–æ–æ–±—â–µ–Ω–∏–µ.
* `media_description` - –û–ø–∏—Å–∞–Ω–∏–µ, —á—Ç–æ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–æ –Ω–∞ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–∏ (–ø—Ä–∏ –Ω–∞–ª–∏—á–∏–∏ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è).

–û—Ç–≤–µ—á–∞–π —Ç–∞–∫ –∂–µ –≤ JSON-—Ñ–æ—Ä–º–∞—Ç–µ, –Ω–æ –∑–∞–ø–æ–ª–Ω—è–π —Ç–æ–ª—å–∫–æ –ø–æ–ª–µ `text` (–∏ `quote`, –µ—Å–ª–∏ –Ω—É–∂–Ω–æ –ø—Ä–æ—Ü–∏—Ç–∏—Ä–æ–≤–∞—Ç—å —á–∞—Å—Ç—å —Å–æ–æ–±—â–µ–Ω–∏—è).
–í –¢–µ–∫—Å—Ç–µ —Å–æ–æ–±—â–µ–Ω–∏—è –º–æ–∂–Ω–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å Markdown —Ñ–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ.
"""
condensing-prompt = """
Your task is to create a detailed summary of the conversation so far.
Output only the summary of the conversation so far, without any
additional commentary or explanation.
Answer using language of conversation, not language of this message."
"""