# https://openrouter.ai/models?fmt=table&max_price=0&order=pricing-low-to-high
[models.models."openrouter/deepseek-chat-v3.1:free"]
# https://openrouter.ai/deepseek/deepseek-chat-v3.1:free
# enabled = false # It rate-limited most of the time, so not sure, that it worth to try it
provider = "openrouter"
model_id = "deepseek/deepseek-chat-v3.1:free"
model_version = "latest"
temparature = 0.3
context = 64000
support_tools = true
support_text = true
support_images = false
can_be_choosen = true

[models.models."openrouter/gemma-3-27b-it:free"]
# https://openrouter.ai/google/gemma-3-27b-it:free
provider = "openrouter"
model_id = "google/gemma-3-27b-it:free"
model_version = "latest"
temparature = 0.3
context = 96000
support_tools = false
support_text = true
support_images = false
can_be_choosen = true

[models.models."openrouter/mistral-7b-instruct:free"]
# https://openrouter.ai/mistralai/mistral-7b-instruct:free
provider = "openrouter"
model_id = "mistralai/mistral-7b-instruct:free"
model_version = "latest"
temparature = 0.3
context = 32768
support_tools = true
support_text = true
support_images = false
can_be_choosen = true

[models.models."openrouter/gpt-oss-20b:free"]
# https://openrouter.ai/openai/gpt-oss-20b:free
enabled = false # rate-limited all the time
provider = "openrouter"
model_id = "openai/gpt-oss-20b:free"
model_version = "latest"
temparature = 0.3
context = 32768
support_tools = true
support_text = true
support_images = false
can_be_choosen = true

[models.models."openrouter/qwen3-235b-a22b:free"]
# https://openrouter.ai/qwen/qwen3-235b-a22b:free
provider = "openrouter"
model_id = "qwen/qwen3-235b-a22b:free"
model_version = "latest"
temparature = 0.3
context = 131100
support_tools = true
support_text = true
support_images = false
can_be_choosen = true