# https://openrouter.ai/models
[models.models."openrouter/claude-sonnet-4"]
provider = "openrouter"
model_id = "anthropic/claude-sonnet-4"
model_version = "latest"
temparature = 0.3
context = 256000
support_tools = true
support_text = true
support_images = false


[models.models."openrouter/deepseek-chat-v3.1"]
provider = "openrouter"
model_id = "deepseek/deepseek-chat-v3.1"
model_version = "latest"
temparature = 0.3
context = 163840
support_tools = true
support_text = true
support_images = false

[models.models."openrouter/qwen-turbo"]
provider = "openrouter"
model_id = "qwen/qwen-turbo"
model_version = "latest"
temparature = 0.3
context = 1000000
support_tools = true
support_text = true
support_images = false

[models.models."openrouter/gemini-2.5-flash-image"]
provider = "openrouter"
model_id = "google/gemini-2.5-flash-image"
model_version = "latest"
temparature = 0.3
context = 32768
support_tools = true
support_text = true
support_images = true