# https://openrouter.ai/models
[models.models."openrouter/deepseek-chat-v3.1-free"]
provider = "openrouter"
model_id = "deepseek/deepseek-chat-v3.1:free"
model_version = "latest"
temparature = 0.3
context = 64000
support_tools = true
support_text = true
support_images = false

[models.models."openrouter/gemma-3-27b-it-free"]
provider = "openrouter"
model_id = "google/gemma-3-27b-it:free"
model_version = "latest"
temparature = 0.3
context = 96000
support_tools = true
support_text = true
support_images = false

[models.models."openrouter/gemma-3-12b-it-free"]
provider = "openrouter"
model_id = "google/gemma-3-12b-it:free"
model_version = "latest"
temparature = 0.3
context = 32768
support_tools = true
support_text = true
support_images = false