[models.providers.yc-openai]
type = "yc-openai"
# https://yandex.cloud/ru/docs/foundation-models/operations/get-api-key
folder_id = "FOLDER_ID"
api_key = "API_KEY"

[models.providers.openrouter]
type = "openrouter"
api_key = "API_KEY"

[models.providers.yc-sdk]
type = "yc-sdk"
folder_id = "FOLDER_ID"
# Optional: specify yc profile (uncomment if needed)
#yc_profile = "profile-id"